### ISSUE TITLE
Configuration view Phase I

### ISSUE THREAD

**Issue by dvayanu** [anotheria/moskito-control-vue#4]
Configuration is a separate Route in the application. 
It is opened from the main application and is blocking (modal) as long as its active. It can be closed again (returns to the main application). 
In the beginning configuration contains three parts:
* Components
* Charts
* Views
They can be displayed as trees or lists, also there are no subnodes. 

![Screenshot 2023-11-21 at 16 58 29](https://github.com/anotheria/moskito-control-vue/assets/2864497/e6c56dc1-7515-48d7-963d-e5c4990ad065)

All elements of the json configuration should be editable. 

Configuration resources is located under /api/v2/configuration (link to swagger follows).
i.e. 
```
http://localhost:8999/api/v2/configuration/components
```
Please see following files for details on the fields. The API will return direct representation of the classes. 
* [Component](https://github.com/anotheria/moskito-control/blob/develop/config/src/main/java/org/moskito/control/config/ComponentConfig.java)
* [Chart](https://github.com/anotheria/moskito-control/blob/develop/config/src/main/java/org/moskito/control/config/ChartConfig.java) and [ChartLine](https://github.com/anotheria/moskito-control/blob/develop/config/src/main/java/org/moskito/control/config/ChartLineConfig.java)
* [View](https://github.com/anotheria/moskito-control/blob/develop/config/src/main/java/org/moskito/control/config/ViewConfig.java) 

## Tasks
* [x] Create Route and general structure.
* [x] Retrieve and show components
* [x] Retrieve and show views.
* [x] Retrieve and show charts
* [x] Delete component
* [x] Update component
* [x] Delete chart
* [x] Update chart
* [x] Delete view
* [x] Update view
